python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0000/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0001/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0002/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0003/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0004/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0005/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0006/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0007/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0008/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0009/
python projects/csim/relocalize.py database/polycam/Oct5at10-49AM-poly/keyframes/images/ database/processed/JPEGImages/Full-Resolution/cat-pikachu-0010/
